package com.aiworkforce.core.enums;
public enum EventType {
    TASK_CREATED, TASK_ASSIGNED, TASK_UPDATED, TASK_COMPLETED, TASK_OVERDUE,
    LEAVE_REQUESTED, LEAVE_APPROVED,
    BURNOUT_FLAG, TASK_COMMENT_ADDED,
    SPRINT_STARTED, SPRINT_COMPLETED,
    WORKLOAD_REBALANCED
}
