name: FOREP Local
values:
  - key: base_url
    value: 'http://localhost:8080'
    enabled: true
  - key: jwt_token
    value: ''
    enabled: true
  - key: employee_id
    value: ''
    enabled: true
  - key: organization_id
    value: ''
    enabled: true
  - key: task_id
    value: ''
    enabled: true
  - key: team_id
    value: ''
    enabled: true
  - key: manager_id
    value: ''
    enabled: true
  - key: sprint_id
    value: ''
    enabled: true
  - key: sprint_number
    value: '1'
    enabled: true
  - key: task_status
    value: TODO
    enabled: true
  - key: leave_status
    value: PENDING
    enabled: true
  - key: leave_id
    value: ''
    enabled: true
  - key: suggestion_id
    value: ''
    enabled: true
