package com.aiworkforce.task.entity;
import com.aiworkforce.core.base.AuditableEntity;
import com.aiworkforce.core.enums.TaskPriority;
import com.aiworkforce.core.enums.TaskStatus;
import com.aiworkforce.identity.entity.Employee;
import com.aiworkforce.identity.entity.Project;
import com.aiworkforce.identity.entity.Team;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import java.time.LocalDateTime;

@Entity
@Table(name = "task")
@Getter
@Setter
public class Task extends AuditableEntity {
    private String title;

    @Column(columnDefinition = "TEXT")
    private String description;

    @Enumerated(EnumType.STRING)
    private TaskStatus status;

    @Enumerated(EnumType.STRING)
    private TaskPriority priority;

    private LocalDateTime dueDate;
    private int estimatedHours;

    @Enumerated(EnumType.STRING)
    private com.aiworkforce.core.enums.IntegrationProvider sourceProvider = com.aiworkforce.core.enums.IntegrationProvider.INTERNAL;

    /** External URL linking directly to the ticket/issue */
    private String externalUrl;

    /** External ticket reference e.g. APX-2117, T-220 */
    private String externalTicketRef;

    /** True when an external provider reports that the item was deleted. */
    private Boolean externalDeleted = false;

    /** Sprint number retained for analytics and external Apex AI views */
    private Integer sprintNumber;

    /** Sprint this task belongs to */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sprint_id")
    private com.aiworkforce.identity.entity.Sprint sprint;

    /** Story points (for velocity calculation) */
    private Integer storyPoints;

    /** Actual time taken to complete the task in days */
    private Double cycleTimeDays;

    /** Actual time taken to complete the task in hours */
    private Double cycleTimeHours;

    /** Difficulty score on a 1-10 scale, generated by the agent or supplied by a lead */
    private Integer difficultyScore;

    /** Overall task score combining task complexity, progress, lead input, and GitHub signals */
    private Double taskScore;

    /** Completion progress percentage from 0-100 */
    private Integer progressPercent;

    /** Team lead's own evaluation, if provided */
    @Column(columnDefinition = "TEXT")
    private String leadEvaluation;

    /** Agent-readable summary of the latest task evaluation */
    @Column(columnDefinition = "TEXT")
    private String assessmentSummary;

    /** Source of the latest evaluation, e.g. MANUAL, AGENT, JIRA_SYNC, GITHUB_SYNC */
    private String assessmentSource;

    /** When this task was last evaluated */
    private LocalDateTime assessedAt;

    /** Number of GitHub commits linked to this task */
    private Integer githubCommitCount;

    /** GitHub commit difficulty score on a 1-10 scale */
    private Integer githubCommitDifficultyScore;

    /** GitHub commit size score on a 1-10 scale */
    private Integer githubCommitSizeScore;

    /** GitHub contribution score folded into the task score */
    private Double githubCommitScore;

    /** When the task was marked completed */
    private LocalDateTime completedAt;

    /** True if this task is on the sprint critical path */
    private Boolean isOnCriticalPath = false;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assignee_id")
    private Employee assignee;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "reporter_id")
    private Employee reporter;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "team_id")
    private Team team;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "project_id")
    private Project project;
}
