$kind: http-request
name: Delete Task (Admin Only)
method: DELETE
url: '{{base_url}}/api/v1/tasks/{{task_id}}'
order: 3100
headers:
  - key: Authorization
    value: 'Bearer {{jwt_token}}'
scripts:
  - type: afterResponse
    language: text/javascript
    code: |-
      pm.test("Status is success", function () {
        pm.expect(pm.response.code).to.be.oneOf([200, 204]);
      });
