$kind: http-request
name: Get Tasks By Employee
method: GET
url: '{{base_url}}/api/v1/tasks/employee/{{employee_id}}'
order: 3020
headers:
  - key: Authorization
    value: 'Bearer {{jwt_token}}'
scripts:
  - type: afterResponse
    language: text/javascript
    code: |-
      pm.test("Status 200 OK", function () {
        pm.response.to.have.status(200);
      });
      pm.test("Tasks response is array", function () {
        pm.expect(pm.response.json().data).to.be.an("array");
      });
