$kind: http-request
name: Update Task
method: PUT
url: '{{base_url}}/api/v1/tasks/{{task_id}}'
order: 3090
headers:
  - key: Authorization
    value: 'Bearer {{jwt_token}}'
  - key: Content-Type
    value: application/json
body:
  mode: raw
  raw: |-
    {
      "title": "Updated task title",
      "description": "Updated task description",
      "priority": "MEDIUM",
      "dueDate": "2026-05-30T17:00:00",
      "estimatedHours": 8,
      "assigneeId": "{{employee_id}}",
      "reporterId": "{{manager_id}}",
      "teamId": "{{team_id}}",
      "sprintId": "{{sprint_id}}",
      "externalTicketRef": "FOREP-UPDATED",
      "sprintNumber": 1,
      "storyPoints": 3
    }
scripts:
  - type: afterResponse
    language: text/javascript
    code: |-
      pm.test("Status 200 OK", function () {
        pm.response.to.have.status(200);
      });
